// file generated by the Paraglide-Next init command
import { PrefixStrategy, Navigation, Middleware } from '@inlang/paraglide-next';
import type { AvailableLanguageTag } from '@/paraglide/runtime';
import * as m from '@/paraglide/messages';
const strategy = PrefixStrategy<AvailableLanguageTag>({
  pathnames: {
    '/login': m.login_path,
    '/register': m.register_path,
  },
  prefixDefault: 'never',

  // don't generate alternate routes for the api
  exclude: (pathname) => {
    return pathname.startsWith('/api/') || pathname === '/api';
  },
});

export const middleware = Middleware({ strategy });
export const { Link, useRouter, usePathname, redirect, permanentRedirect } =
  Navigation({ strategy });
