version: "3.8"
services:
    db:
        image: postgres:15
        container_name: genio_frontend
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "04012002"
            POSTGRES_DB: genio_db
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5435:5432"
volumes:
    db_data:
        name: genio_frontend
